version: '3'
services:
  db:
    image: postgres:11
    restart: always
    environment:
      POSTGRES_DB: medstack
      POSTGRES_USER: medstack
      POSTGRES_PASSWORD: medstack
  medstack:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - db
    environment:
      RACK_ENV: development
      DOCKER_URL: unix:///var/run/docker.sock
      DATABASE_URL: postgres://medstack:medstack@db/medstack
      APP_SESSION_SECRET: 26zH8QbcEqWiThz/dKc4vnHSc+p8bJM312/43Y4Yka3o2kbfswDVmh+vsNYJoIO7M4trEEAjOfGYm+4GEk3j7w==